hyperweb-io/telescope

README.md
packages/telescope/README.md
packages/telescope/__tests__/telescope.test.ts
packages/telescope/src/generators/create-bundle.ts
packages/types/src/telescope.ts
packages/types/types/telescope.d.ts

add bundle option

---

__fixtures__/output1/cosmos/distribution/v1beta1/query.lcd.ts
__fixtures__/output1/cosmos/gov/v1/query.lcd.ts
__fixtures__/output1/cosmos/gov/v1beta1/query.lcd.ts
__fixtures__/output1/cosmos/staking/v1beta1/query.lcd.ts
__fixtures__/output1/cosmwasm/wasm/v1/query.lcd.ts
__fixtures__/output1/ibc/core/channel/v1/query.lcd.ts
__fixtures__/output1/ibc/core/client/v1/query.lcd.ts
__fixtures__/output1/ibc/core/connection/v1/query.lcd.ts
packages/ast/package.json
packages/ast/src/clients/lcd/class/__snapshots__/lcd.test.ts.snap
packages/ast/src/clients/lcd/class/__snapshots__/template-tag.test.ts.snap
packages/ast/src/clients/lcd/class/lcd.keepCase.test.ts
packages/ast/src/clients/lcd/class/lcd.test.ts
packages/ast/src/clients/lcd/class/lcd.ts
packages/ast/src/clients/lcd/class/template-tag.test.ts
packages/ast/types/src/clients/lcd/class/lcd.d.ts
packages/ast/types/src/clients/lcd/class/template-tag.test.d.ts

template tags

---

packages/ast/src/state/mobx/__snapshots__/mobx.scoped.test.ts.snap
packages/ast/src/state/mobx/__snapshots__/mobx.test.ts.snap
packages/ast/src/state/mobx/mobx.test.ts
packages/ast/src/state/mobx/mobx.ts
packages/ast/src/state/mobx/scoped-bundle.ts
packages/ast/src/state/react-query/react-query.ts
packages/ast/src/utils/scoped-bundle-builder.ts

finished ast changes in the package of AST and well tested and commented.

Mobx plugin

---

README.md
packages/parser/src/utils.ts
packages/telescope/types/cmds.d.ts
packages/types/src/telescope.ts
packages/types/types/base.d.ts
packages/types/types/telescope.d.ts

add more doc in Readme.md
fixed comments
updated defination files
also marked patterns fields inside "include" as deprecated

complete docs and comments

---

packages/test/src/test-lcd-balance.ts

add balance and accounts test for lcd

add more lcd test

---

packages/ast/src/encoding/proto/__snapshots__/proto.type.spec.ts.snap
packages/ast/src/encoding/proto/proto.type.spec.ts
packages/ast/src/encoding/types.ts

replace more undefined fields following this [issue](https://github.com/osmosis-labs/telescope/issues/403)

add case for Timestamp and Date & remove `undefined` for duration, coin in createCreateProtoType

---

packages/telescope/src/cli.js

add -v option to show version for telescope
show version when executing telescope cmd

add -v and show version when start

---

packages/telescope/src/commands/transpile.ts

https://github.com/cosmology-tech/telescope/issues/491
users can use:
```
telescope transpile --config a.json --config b.json
```
values in config afterward will override those in front. 
e.g.: prototype.typingsFormat.num64: "bigint" in b.json will override the same field in a.json.

support multi config

---

__fixtures__/misc/output-impl-interfaces-gen/cosmos/authz/v1beta1/authz.ts
__fixtures__/misc/output-impl-interfaces-gen/google/protobuf/descriptor.ts
packages/ast/src/encoding/__tests__/__snapshots__/misc.overall.test.ts.snap
packages/ast/src/encoding/proto/is/index.ts
packages/ast/types/encoding/proto/is/index.d.ts

use isSet to check whether an enum is existing.

fix enum check in is method

---

__fixtures__/misc/output-impl-interfaces-gen/cosmos/authz/v1beta1/authz.ts
__fixtures__/misc/output-proto-amino/amino-interface-proto-optionality/misc/eval_request.ts
__fixtures__/misc/output-proto-amino/amino-interface/misc/eval_request.ts
__fixtures__/misc/proto-impl-interfaces/cosmos/authz/v1beta1/authz.proto
packages/ast/src/encoding/proto/from-partial/utils.ts
packages/ast/types/encoding/proto/from-partial/utils.d.ts

Fixed repeated Any type fields with impl interface can't compile.

fix impl interface array field bug

---

packages/starship/__tests__/v1/authz.test.ts
packages/starship/__tests__/v1/staking.test.ts

add staking and authz v1 starship e2e test

add staking and authz v1

---

__fixtures__/v-next/outputinstantrpc/react-query.ts
__fixtures__/v-next/outputv4/react-query.ts
packages/telescope/src/helpers/react-query.ts

use connectComet in useTendermintClient

fix connect comet in react query helper

---

__fixtures__/misc/output-proto-amino/amino-interface-proto-optionality/google/protobuf/any.ts
__fixtures__/misc/output-proto-amino/amino-interface/google/protobuf/any.ts
__fixtures__/misc/output-proto-amino/amino-legacy/google/protobuf/any.ts
__fixtures__/misc/output-proto-amino/amino-msg-no-func/google/protobuf/any.ts
__fixtures__/misc/output-proto-amino/amino-msg-with-func/google/protobuf/any.ts
__fixtures__/misc/output-proto-amino/amino-no-msg-with-func/google/protobuf/any.ts
__fixtures__/misc/output-proto-amino/no-amino-legacy-no-proto/google/protobuf/any.ts
__fixtures__/misc/output-proto-amino/no-amino-legacy/google/protobuf/any.ts
__fixtures__/misc/output-proto-amino/no-amino-no-proto/google/protobuf/any.ts
__fixtures__/misc/output-proto-amino/no-amino/google/protobuf/any.ts
__fixtures__/misc/output-proto-amino/proto-only-legacy/google/protobuf/any.ts
__fixtures__/misc/output-proto-amino/proto-only/google/protobuf/any.ts
__fixtures__/misc/output/google/protobuf/any.ts
__fixtures__/v-next/outputinstantrpc/google/protobuf/any.ts
__fixtures__/v-next/outputosmojs/google/protobuf/any.ts
__fixtures__/v-next/outputsign/google/protobuf/any.ts
__fixtures__/v-next/outputv2/cosmos/auth/v1beta1/query.ts
__fixtures__/v-next/outputv2/cosmos/authz/v1beta1/tx.ts
__fixtures__/v-next/outputv2/cosmos/gov/v1/tx.ts
__fixtures__/v-next/outputv2/google/protobuf/any.ts
__fixtures__/v-next/outputv2/osmosis/gamm/v1beta1/genesis.ts
__fixtures__/v-next/outputv2/osmosis/gamm/v1beta1/query.ts
__fixtures__/v-next/outputv3/google/protobuf/any.ts
__fixtures__/v-next/outputv4/google/protobuf/any.ts
packages/ast/src/encoding/proto/decode/utils.ts
packages/ast/src/encoding/proto/implements/__tests__/__snapshots__/interface-decoder.test.ts.snap
packages/ast/src/encoding/proto/interface/__tests__/__snapshots__/google.proto.any.test.ts.snap
packages/ast/src/encoding/proto/interface/proto.ts

fix Any() in decode function
fix $typeurl for Any type.

fix $typeurl for Any type and decode function bug

---

.github/workflows/run-e2e-tests.yaml
packages/starship/Makefile
packages/starship/__tests__/v0/gov.test.ts
packages/starship/__tests__/v1/authz.test.ts
packages/starship/__tests__/v1/gov.test.ts
packages/starship/package.json

Set expiration for the authz grants to make the test work.

fix: fix authz tests

---

packages/telescope/src/parse.ts

Not much but I was investigating a problem with my protobufs and telescope and this led me astray for some minutes 😁

fix error message for response type lookup

---

README.md

```diff
akash: {
stargateClients: {
-            enabled: true;
-            includeCosmosDefaultTypes: false;
+            enabled: true,
+            includeCosmosDefaultTypes: false
},
```

Fix typos in README.md (`;` -> `,`)

---

packages/lcd/package.json
packages/starship/package.json

Fixes https://github.com/advisories/GHSA-8hc4-vh64-cxmj
Fixes #644

chore(deps): bump axios to `1.7.4`

---

README.md
__fixtures__/v-next/outputinstantrpc/akash-cosmos-client.ts
__fixtures__/v-next/outputinstantrpc/cosmos-ibc-client.ts
packages/telescope/README.md
packages/telescope/__tests__/telescope-instant-rpc.test.ts
packages/telescope/src/builder.ts
packages/telescope/src/generators/create-combined-stargate-clients.ts
packages/telescope/src/generators/create-stargate-clients.ts
packages/telescope/types/generators/create-combined-stargate-clients.d.ts
packages/types/src/telescope.ts
packages/types/types/telescope.d.ts
packages/utils/src/proto.ts
packages/utils/types/proto.d.ts

Added generation for combined clients in root directory

---

README.md
__fixtures__/v-next/outputinstantrpc/akash-sdk-module-client.ts
__fixtures__/v-next/outputinstantrpc/all-module-client.ts
__fixtures__/v-next/outputinstantrpc/cosmos-sdk-module-client.ts
__fixtures__/v-next/outputinstantrpc/custom-client.ts
__fixtures__/v-next/outputinstantrpc/index.ts
__fixtures__/v-next/outputinstantrpc/osmosis-sdk-module-client.ts
packages/telescope/README.md
packages/telescope/__tests__/telescope-instant-rpc.test.ts
packages/telescope/src/builder.ts
packages/telescope/src/generators/create-all-stargate-clients.ts
packages/telescope/src/generators/create-custom-stargate-clients.ts
packages/telescope/src/generators/create-index.ts
packages/telescope/src/generators/create-sdk-module-stargate-clients.ts
packages/telescope/types/generators/create-all-stargate-clients.d.ts
packages/telescope/types/generators/create-custom-stargate-clients.d.ts
packages/telescope/types/generators/create-scoped-stargate-clients.d.ts
packages/telescope/types/generators/create-sdk-module-stargate-clients.d.ts
packages/telescope/types/generators/create-unified-stargate-clients.d.ts
packages/types/src/telescope.ts
packages/types/types/telescope.d.ts

Reorganization of client style option with all, sdk-module, custom

---

__fixtures__/misc/output-impl-interfaces-gen/cosmos/base/v1beta1/coin.ts
__fixtures__/misc/proto/misc/eval_request.proto
__fixtures__/v-next/outputhelperfunc/cosmos/base/v1beta1/coin.ts
__fixtures__/v-next/outputicjs/cosmos/base/v1beta1/coin.ts
__fixtures__/v-next/outputinstantrpc/cosmos/base/v1beta1/coin.ts
__fixtures__/v-next/outputosmojs/cosmos/base/v1beta1/coin.ts
__fixtures__/v-next/outputsign/cosmos/base/v1beta1/coin.ts
__fixtures__/v-next/outputv2/cosmos/base/v1beta1/coin.ts
__fixtures__/v-next/outputv3/cosmos/base/v1beta1/coin.ts
__fixtures__/v-next/outputv4/cosmos/base/v1beta1/coin.ts
packages/ast/src/encoding/amino/to-amino-json/utils.ts
packages/ast/src/encoding/proto/decode/utils.ts
packages/ast/src/encoding/proto/encode/utils.ts
packages/ast/src/encoding/proto/to-amino/utils.ts
packages/ast/types/encoding/proto/encode/utils.d.ts
packages/parser/src/traverse.ts
packages/parser/types/traverse.d.ts
packages/types/src/base.ts
packages/types/types/base.d.ts

take the go package into the consideration:
option go_package                       = "github.com/cosmos/cosmos-sdk/types";
when go_package == "github.com/cosmos/cosmos-sdk/types" && (gogoproto.customtype) == "Dec"
The code will also be generated as the same with "github.com/cosmos/cosmos-sdk/types.Dec"

fixed go_package handling
